export const commonContent = {
  loading: "Loading...",
  error: "An error occurred. Please try again.",
  success: "Success!",
  cancel: "Cancel",
  save: "Save",
  edit: "Edit",
  delete: "Delete",
  confirm: "Confirm",
  back: "Back",
  next: "Next",
  previous: "Previous",
  close: "Close",
  submit: "Submit",
  search: "Search",
  filter: "Filter",
  clear: "Clear",
  view: "View",
  join: "Join",
  leave: "Leave",
  apply: "Apply",
  learnMore: "Learn More",
  noResults: "No results found",
  noData: "No data available",
  yes: "Yes",
  no: "No",
  ok: "OK",
  retry: "Retry",
  refresh: "Refresh",
  update: "Update",
  create: "Create",
  add: "Add",
  remove: "Remove",
  select: "Select",
  choose: "Choose",
  upload: "Upload",
  download: "Download",
  share: "Share",
  copy: "Copy",
  paste: "Paste",
  undo: "Undo",
  redo: "Redo",
  expand: "Expand",
  collapse: "Collapse",
  show: "Show",
  hide: "Hide",
  enable: "Enable",
  disable: "Disable",
  active: "Active",
  inactive: "Inactive",
  online: "Online",
  offline: "Offline",
  public: "Public",
  private: "Private",
  open: "Open",
  closed: "Closed",
  available: "Available",
  unavailable: "Unavailable",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  completed: "Completed",
  inProgress: "In Progress",
  scheduled: "Scheduled",
  cancelled: "Cancelled",
  expired: "Expired",
  archived: "Archived",
  draft: "Draft",
  published: "Published",
  unpublished: "Unpublished"
};